### ISSUE TITLE
Not working with Redis version 4.5.2

### ISSUE THREAD

**Issue by rajkumar21Virim** [yahoo/redislite#171]
With Redis version 4.5.2, I am getting IndexError: pop from empty list.
I had to downgrade Redis back to redis==4.4.1 to make it work again.

Error logs for the Redis version 4.5.2 attached below:

`sed unexpected: TypeError("__init__() got an unexpected keyword argument 'socket_timeout'")
edi_file_processor_worker    | Traceback (most recent call last):
edi_file_processor_worker    |   File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 1434, in get_connection
edi_file_processor_worker    |     connection = self._available_connections.pop()
edi_file_processor_worker    | IndexError: pop from empty list
edi_file_processor_worker    | 
edi_file_processor_worker    | During handling of the above exception, another exception occurred:
edi_file_processor_worker    | 
edi_file_processor_worker    | Traceback (most recent call last):
edi_file_processor_worker    |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 451, in trace_task
edi_file_processor_worker    |     R = retval = fun(*args, **kwargs)
edi_file_processor_worker    |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 734, in __protected_call__
edi_file_processor_worker    |     return self.run(*args, **kwargs)
edi_file_processor_worker    |     return self.db.hgetall(id)
edi_file_processor_worker    |   File "/edi/utility_and_packages/master_utility/src/utility.py", line 340, in db
edi_file_processor_worker    |     self.__db_connection = Redis(self.latest_log_file_path, decode_responses=True)
edi_file_processor_worker    |   File "/usr/local/lib/python3.8/site-packages/redislite/client.py", line 395, in __init__
edi_file_processor_worker    |     self._wait_for_server_start()
edi_file_processor_worker    |   File "/usr/local/lib/python3.8/site-packages/redislite/client.py", line 217, in _wait_for_server_start
edi_file_processor_worker    |     self.ping()
edi_file_processor_worker    |   File "/usr/local/lib/python3.8/site-packages/redis/commands/core.py", line 1194, in ping
edi_file_processor_worker    |     return self.execute_command("PING", **kwargs)
edi_file_processor_worker    |   File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1255, in execute_command
edi_file_processor_worker    |     conn = self.connection or pool.get_connection(command_name, **options)
edi_file_processor_worker    |   File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 1436, in get_connection
edi_file_processor_worker    |     connection = self.make_connection()
edi_file_processor_worker    |   File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 1476, in make_connection
edi_file_processor_worker    |     return self.connection_class(**self.connection_kwargs)
edi_file_processor_worker    |   File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 1160, in __init__
edi_file_processor_worker    |     super().__init__(**kwargs)
edi_file_processor_worker    | TypeError: __init__() got an unexpected keyword argument 'socket_timeout'
`

**Comment by lioman** [comment]
Same issue for `4.5.3`

**Comment by dwighthubbard** [comment]
This issue isn't occurring with redis-py 5.0.0 so it appears the issue is fixed there and I'm going to close this issue since the problem isn't in redislite itself.
